# SPDX-FileCopyrightText: Copyright (c) [2025-2026] [Sergei Mukhin]
# SPDX-License-Identifier: MIT
---
name: copyrights
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  copyrights:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: yegor256/copyrights-action@0.0.12
        with:
          license: LICENSE.txt
          globs: >-
            src/**/*.cs
            **/*.yml
